baseurl = "http://www.philipcstevens.com"
title = "Philip C. Stevens"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

#pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Philip C. Stevens"
    info = "Data Scientist and Machine Learning Engineer"
    description = "Phil Stevens' personal website"
    keywords = "blog,developer,personal,data scientist,machine learning"
    avatarurl = "images/headshot.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = "A professional website for Philip C. Stevens."

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/philipstevens/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://www.linkedin.com/in/philip-stevens-853b9437/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about/"
[[menu.main]]
    name = "Contact"
    weight = 4
    url = "/contact/"
[[menu.main]]
    name = "Projects"
    weight = 3
    url = "/projects/"

[markup]
  [markup.highlight]
    codeFences = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4

[deployment]
[[deployment.targets]]
    name = "s3-deployment"
    URL = "s3://www.philipcstevens.com?region=us-west-2"
